# Generated by Django 2.2.2 on 2019-06-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(choices=[('ch', 'Chocolate'), ('cc', 'Cenoura com chocolate'), ('se', 'Sensação'), ('pr', 'Prestigio'), ('nh', 'Ninho'), ('cr', 'Churros'), ('ba', 'Banana')], max_length=2)),
                ('recheio', models.CharField(choices=[('br', 'Brigadeiro'), ('bj', 'Beijinho'), ('dl', 'Doce de Leite'), ('fv', 'Frutas Vermelhas'), ('nu', 'Nutella'), ('ni', 'Ninho'), ('fr', 'Frutas')], max_length=2)),
                ('cobertura', models.CharField(choices=[('gr', 'Granulado'), ('ct', 'Chantilly'), ('mr', 'Morango'), ('sm', 'Sem Cobertura')], default='sm', max_length=2)),
                ('peso', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=200)),
                ('cartao', models.IntegerField()),
                ('pagamento', models.CharField(choices=[('av', 'Pagamento à vista'), ('p2', 'Parcelado em 2 vezes'), ('p3', 'Parcelado em 3 vezes')], default='av', max_length=2)),
            ],
        ),
    ]
