# Generated by Django 2.2.2 on 2019-06-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolo',
            name='cobertura',
            field=models.CharField(choices=[('gr', 'Granulado'), ('ct', 'Chantilly'), ('mr', 'Morango'), ('sm', 'Sem Cobertura'), ('br', 'Brigadeiro')], default='sm', max_length=2),
        ),
        migrations.AlterField(
            model_name='bolo',
            name='sabor',
            field=models.CharField(choices=[('ch', 'Chocolate'), ('ce', 'Cenoura'), ('se', 'Sensação'), ('pr', 'Prestigio'), ('nh', 'Ninho'), ('cr', 'Churros'), ('ba', 'Banana')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cartao',
            field=models.IntegerField(max_length=16),
        ),
    ]
