# Generated by Django 2.2.2 on 2019-06-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0002_auto_20190628_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cartao',
            field=models.IntegerField(),
        ),
    ]
